apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: grafana
  name: grafana
spec:
  containers:
  - image: grafana/grafana
    name: grafana
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
