apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: promdeploy
  name: promdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promdeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: promdeploy
    spec:
      containers:
      - image: prom/prometheus
        name: prometheus
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/etc/prometheus/"
        ports:
          - containerPort: 9090
        volumeMounts:
         - name: promdata
           mountPath: /etc/prometheus
      volumes:
        - name: promdata
          emptyDir: {}

